#version: "3.9"

services:
  db:
    image: postgres:15
    container_name: odoo19_db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - odoo19_pgdata:/var/lib/postgresql/data

  odoo:
    image: odoo:19
    container_name: odoo19
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      ADMIN_PASSWORD: Lorenaluiz1
    volumes:
      - ../custom-addons:/mnt/extra-addons
#      - ../config/:/etc/odoo
#      - ../config/odoo.conf:/etc/odoo/odoo.conf
    command: >
      odoo
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    restart: always

#volumes:
#  odoo19_pgdata: